name: social_app
description: A new Flutter project.
publish_to: none
version: 1.0.0+1
environment:
    sdk: '>=2.17.0 <3.0.0'
dependencies:
    flutter:
        sdk: flutter
    firebase_auth: ^4.3.0
    firebase_core: ^2.8.0
    get: ^4.6.5
    google_fonts: ^4.0.3
    cloud_firestore: ^4.4.5
    get_storage: ^2.1.1
    animated_icon_button: ^1.0.2
    cached_network_image: ^3.2.3
    firebase_storage: ^11.0.16
    image_picker: ^0.8.7+1
    firebase_database: ^10.1.0
    flutter_svg: ^2.0.4
dev_dependencies:
    icons_launcher: ^2.1.0
    flutter_lints: ^2.0.1
    flutter_test:
        sdk: flutter
flutter:
    uses-material-design: true


    assets:
    - assets/logo/
    - assets/images/

icons_launcher:
  image_path: "assets/logo/chat_logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true
